apiVersion: triliovault.trilio.io/v1
kind: TrilioVaultManager
metadata:
  labels:
    triliovault: triliovault
  name: triliovault-manager
  namespace: default
spec:
  trilioVaultAppVersion: 1.1.1
  helmVersion:
    version: v3
  applicationScope: Cluster
  #restoreNamespaces: ["kube-system", "default", "restore-ns"]
  #resources:
    #requests:
      #memory: 400Mi
